---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident Protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: Personalice la configuración predeterminada de Trident Protect para satisfacer sus necesidades específicas. 
---
= Personalizar la instalación de Trident Protect
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede personalizar la configuración predeterminada de Trident Protect para satisfacer los requisitos específicos de su entorno.



== Especificar los límites de recursos del contenedor Trident Protect

Puede utilizar un archivo de configuración para especificar límites de recursos para los contenedores de Trident Protect después de instalar Trident Protect. Establecer límites de recursos le permite controlar qué cantidad de recursos del clúster consumen las operaciones de Trident Protect.

.Pasos
. Crear un archivo llamado `resourceLimits.yaml`.
. Complete el archivo con opciones de límite de recursos para los contenedores de Trident Protect según las necesidades de su entorno.
+
El siguiente archivo de configuración de ejemplo muestra la configuración disponible y contiene los valores predeterminados para cada límite de recursos:

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. Aplique los valores del `resourceLimits.yaml` archivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== Personalizar restricciones de contexto de seguridad

Puede utilizar un archivo de configuración para modificar la restricción de contexto de seguridad (SCC) de OpenShift para los contenedores de Trident Protect después de instalar Trident Protect. Estas restricciones definen las limitaciones de seguridad para los pods en un clúster de Red Hat OpenShift.

.Pasos
. Crear un archivo llamado `sccconfig.yaml`.
. Agregue la opción SCC al archivo y modifique los parámetros según las necesidades de su entorno.
+
El siguiente ejemplo muestra los valores predeterminados de los parámetros para la opción SCC:

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
En esta tabla se describen los parámetros de la opción SCC:

+
|===
| Parámetro | Descripción | Predeterminado 


| cree | Determina si se puede crear un recurso SCC. Un recurso de SCC se creará sólo si `scc.create` se establece en `true` y el proceso de instalación de Helm identifica un entorno de OpenShift. Si no funciona en OpenShift, o si `scc.create` está establecido en `false`, no se creará ningún recurso SCC. | verdadero 


| nombre | Especifica el nombre del SCC. | Trident-protect-job 


| prioridad | Define la prioridad del SCC. Los SCCS con valores de prioridad más altos se evalúan antes que aquellos con valores más bajos. | 1 
|===
. Aplique los valores del `sccconfig.yaml` archivo:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
Esto reemplazará los valores predeterminados por los especificados en el `sccconfig.yaml` archivo.





== Configurar conexiones de NetApp AutoSupport para Trident Protect

Puede cambiar la forma en que Trident Protect se conecta al soporte de NetApp para cargar paquetes de soporte configurando un proxy para la conexión.  Puede configurar el proxy para utilizar una conexión segura o insegura según sus necesidades.

[role="tabbed-block"]
====
.Configure una conexión proxy segura
--
.Pasos
. Configure una conexión de proxy segura para las cargas de paquetes de soporte de Trident Protect:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --reuse-values
----


--
.Configurar una conexión de proxy no segura
--
.Pasos
. Configure una conexión de proxy insegura para las cargas de paquetes de soporte de Trident Protect que omite la verificación TLS:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --set autoSupport.insecure=true --reuse-values
----


--
====


== Restringir los pods de Trident Protect a nodos específicos

Puede utilizar la restricción de selección de nodos nodeSelector de Kubernetes para controlar cuáles de sus nodos son elegibles para ejecutar pods de Trident Protect, según las etiquetas de los nodos. De forma predeterminada, Trident Protect está restringido a los nodos que ejecutan Linux. Puedes personalizar aún más estas restricciones según tus necesidades.

.Pasos
. Crear un archivo llamado `nodeSelectorConfig.yaml`.
. Agregue la opción nodeSelector al archivo y modifique el archivo para agregar o cambiar etiquetas de nodo para restringir según las necesidades del entorno. Por ejemplo, el siguiente archivo contiene la restricción predeterminada del sistema operativo, pero también se dirige a una región y un nombre de aplicación específicos:
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. Aplique los valores del `nodeSelectorConfig.yaml` archivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
Esto reemplaza las restricciones predeterminadas por las especificadas en el `nodeSelectorConfig.yaml` archivo.





== Deshabilitar las cargas diarias de paquetes de AutoSupport de Trident Protect

De manera opcional, puede deshabilitar las cargas diarias programadas del paquete de soporte de Trident Protect AutoSupport .


NOTE: De forma predeterminada, Trident Protect recopila información de soporte que ayuda con cualquier caso de soporte de NetApp que pueda abrir, incluidos registros, métricas e información de topología sobre clústeres y aplicaciones administradas.  Trident Protect envía estos paquetes de soporte a NetApp según una programación diaria.  Puedes hacerlo manualmentelink:trident-protect-generate-support-bundle.html["generar un bundle de soporte"] en cualquier momento.

.Pasos
. Crear un archivo llamado `autosupportconfig.yaml`.
. Añada la opción AutoSupport al archivo y modifique los parámetros según las necesidades de su entorno.
+
En el siguiente ejemplo, se muestran los valores predeterminados de los parámetros para la opción AutoSupport:

+
[source, yaml]
----
autoSupport:
  enabled: true
----
+
Cuando `autoSupport.enabled` se configura en `false`, se deshabilitan las cargas diarias de paquetes de soporte de AutoSupport.

. Aplique los valores del `autosupportconfig.yaml` archivo:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f autosupportconfig.yaml --reuse-values
----

